name: medico
description: "Take medical appointments with this app"
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  provider: ^6.1.5
  dio: ^5.8.0+1
  get_it: ^8.0.3
  jwt_decode: ^0.3.1
  http: ^1.4.0
  flutter_secure_storage: ^9.2.4
  email_otp: ^3.0.2
  board_datetime_picker: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.3
  json_serializable: ^6.9.5
  flutter_launcher_icons: 0.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
flutter_icons:
  android: "launcher_icon"
  ios: true
  min_sdk_android: 29
  image_path: "assets/logo/medico_logo_official.png"
  remove_alpha_channel_ios: true
  remove_alpha_ios: true
