name: medico
description: "Take medical appointments with this app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  provider: ^6.1.5
  dio: ^5.8.0+1
  get_it: ^8.0.3
  flutter_secure_storage: ^4.2.1
  jwt_decode: ^0.3.1
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.3
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
