name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'  # Change to 'beta' if needed

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: flutter format --set-exit-if-changed . || echo "Format issues detected"

      - name: Build APK
        run: flutter build apk --release --dart-define HOST="https://jspemic.pythonanywhere.com"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: medico-apk
          path: build/app/outputs/flutter-apk/app-release.apk
